//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_App.ServiceReferenceSoap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private bool IsRetiredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool IsRetired {
            get {
                return this.IsRetiredField;
            }
            set {
                if ((this.IsRetiredField.Equals(value) != true)) {
                    this.IsRetiredField = value;
                    this.RaisePropertyChanged("IsRetired");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSoap.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WPF_App.ServiceReferenceSoap.HelloWorldResponse HelloWorld(WPF_App.ServiceReferenceSoap.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.HelloWorldResponse> HelloWorldAsync(WPF_App.ServiceReferenceSoap.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelsius", ReplyAction="*")]
        double FahrenheitToCelsius(double tempFahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FahrenheitToCelsius", ReplyAction="*")]
        System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double tempFahrenheit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFahrenheit", ReplyAction="*")]
        double CelsiusToFahrenheit(double tempCelsius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CelsiusToFahrenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double tempCelsius);
        
        // CODEGEN: Generating message contract since element name ReadUserDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadUserData", ReplyAction="*")]
        WPF_App.ServiceReferenceSoap.ReadUserDataResponse ReadUserData(WPF_App.ServiceReferenceSoap.ReadUserDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadUserData", ReplyAction="*")]
        System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.ReadUserDataResponse> ReadUserDataAsync(WPF_App.ServiceReferenceSoap.ReadUserDataRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUserData", ReplyAction="*")]
        WPF_App.ServiceReferenceSoap.CreateUserDataResponse CreateUserData(WPF_App.ServiceReferenceSoap.CreateUserDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUserData", ReplyAction="*")]
        System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.CreateUserDataResponse> CreateUserDataAsync(WPF_App.ServiceReferenceSoap.CreateUserDataRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserData", ReplyAction="*")]
        WPF_App.ServiceReferenceSoap.UpdateUserDataResponse UpdateUserData(WPF_App.ServiceReferenceSoap.UpdateUserDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserData", ReplyAction="*")]
        System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.UpdateUserDataResponse> UpdateUserDataAsync(WPF_App.ServiceReferenceSoap.UpdateUserDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WPF_App.ServiceReferenceSoap.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WPF_App.ServiceReferenceSoap.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPF_App.ServiceReferenceSoap.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WPF_App.ServiceReferenceSoap.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadUserDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadUserData", Namespace="http://tempuri.org/", Order=0)]
        public WPF_App.ServiceReferenceSoap.ReadUserDataRequestBody Body;
        
        public ReadUserDataRequest() {
        }
        
        public ReadUserDataRequest(WPF_App.ServiceReferenceSoap.ReadUserDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReadUserDataRequestBody {
        
        public ReadUserDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadUserDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadUserDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPF_App.ServiceReferenceSoap.ReadUserDataResponseBody Body;
        
        public ReadUserDataResponse() {
        }
        
        public ReadUserDataResponse(WPF_App.ServiceReferenceSoap.ReadUserDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadUserDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPF_App.ServiceReferenceSoap.UserData ReadUserDataResult;
        
        public ReadUserDataResponseBody() {
        }
        
        public ReadUserDataResponseBody(WPF_App.ServiceReferenceSoap.UserData ReadUserDataResult) {
            this.ReadUserDataResult = ReadUserDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserData", Namespace="http://tempuri.org/", Order=0)]
        public WPF_App.ServiceReferenceSoap.CreateUserDataRequestBody Body;
        
        public CreateUserDataRequest() {
        }
        
        public CreateUserDataRequest(WPF_App.ServiceReferenceSoap.CreateUserDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPF_App.ServiceReferenceSoap.UserData requestData;
        
        public CreateUserDataRequestBody() {
        }
        
        public CreateUserDataRequestBody(WPF_App.ServiceReferenceSoap.UserData requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPF_App.ServiceReferenceSoap.CreateUserDataResponseBody Body;
        
        public CreateUserDataResponse() {
        }
        
        public CreateUserDataResponse(WPF_App.ServiceReferenceSoap.CreateUserDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPF_App.ServiceReferenceSoap.UserData CreateUserDataResult;
        
        public CreateUserDataResponseBody() {
        }
        
        public CreateUserDataResponseBody(WPF_App.ServiceReferenceSoap.UserData CreateUserDataResult) {
            this.CreateUserDataResult = CreateUserDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserData", Namespace="http://tempuri.org/", Order=0)]
        public WPF_App.ServiceReferenceSoap.UpdateUserDataRequestBody Body;
        
        public UpdateUserDataRequest() {
        }
        
        public UpdateUserDataRequest(WPF_App.ServiceReferenceSoap.UpdateUserDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPF_App.ServiceReferenceSoap.UserData requestData;
        
        public UpdateUserDataRequestBody() {
        }
        
        public UpdateUserDataRequestBody(WPF_App.ServiceReferenceSoap.UserData requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public WPF_App.ServiceReferenceSoap.UpdateUserDataResponseBody Body;
        
        public UpdateUserDataResponse() {
        }
        
        public UpdateUserDataResponse(WPF_App.ServiceReferenceSoap.UpdateUserDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WPF_App.ServiceReferenceSoap.UserData UpdateUserDataResult;
        
        public UpdateUserDataResponseBody() {
        }
        
        public UpdateUserDataResponseBody(WPF_App.ServiceReferenceSoap.UserData UpdateUserDataResult) {
            this.UpdateUserDataResult = UpdateUserDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WPF_App.ServiceReferenceSoap.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WPF_App.ServiceReferenceSoap.WebServiceSoap>, WPF_App.ServiceReferenceSoap.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_App.ServiceReferenceSoap.HelloWorldResponse WPF_App.ServiceReferenceSoap.WebServiceSoap.HelloWorld(WPF_App.ServiceReferenceSoap.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WPF_App.ServiceReferenceSoap.HelloWorldRequest inValue = new WPF_App.ServiceReferenceSoap.HelloWorldRequest();
            inValue.Body = new WPF_App.ServiceReferenceSoap.HelloWorldRequestBody();
            WPF_App.ServiceReferenceSoap.HelloWorldResponse retVal = ((WPF_App.ServiceReferenceSoap.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.HelloWorldResponse> WPF_App.ServiceReferenceSoap.WebServiceSoap.HelloWorldAsync(WPF_App.ServiceReferenceSoap.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.HelloWorldResponse> HelloWorldAsync() {
            WPF_App.ServiceReferenceSoap.HelloWorldRequest inValue = new WPF_App.ServiceReferenceSoap.HelloWorldRequest();
            inValue.Body = new WPF_App.ServiceReferenceSoap.HelloWorldRequestBody();
            return ((WPF_App.ServiceReferenceSoap.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public double FahrenheitToCelsius(double tempFahrenheit) {
            return base.Channel.FahrenheitToCelsius(tempFahrenheit);
        }
        
        public System.Threading.Tasks.Task<double> FahrenheitToCelsiusAsync(double tempFahrenheit) {
            return base.Channel.FahrenheitToCelsiusAsync(tempFahrenheit);
        }
        
        public double CelsiusToFahrenheit(double tempCelsius) {
            return base.Channel.CelsiusToFahrenheit(tempCelsius);
        }
        
        public System.Threading.Tasks.Task<double> CelsiusToFahrenheitAsync(double tempCelsius) {
            return base.Channel.CelsiusToFahrenheitAsync(tempCelsius);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_App.ServiceReferenceSoap.ReadUserDataResponse WPF_App.ServiceReferenceSoap.WebServiceSoap.ReadUserData(WPF_App.ServiceReferenceSoap.ReadUserDataRequest request) {
            return base.Channel.ReadUserData(request);
        }
        
        public WPF_App.ServiceReferenceSoap.UserData ReadUserData() {
            WPF_App.ServiceReferenceSoap.ReadUserDataRequest inValue = new WPF_App.ServiceReferenceSoap.ReadUserDataRequest();
            inValue.Body = new WPF_App.ServiceReferenceSoap.ReadUserDataRequestBody();
            WPF_App.ServiceReferenceSoap.ReadUserDataResponse retVal = ((WPF_App.ServiceReferenceSoap.WebServiceSoap)(this)).ReadUserData(inValue);
            return retVal.Body.ReadUserDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.ReadUserDataResponse> WPF_App.ServiceReferenceSoap.WebServiceSoap.ReadUserDataAsync(WPF_App.ServiceReferenceSoap.ReadUserDataRequest request) {
            return base.Channel.ReadUserDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.ReadUserDataResponse> ReadUserDataAsync() {
            WPF_App.ServiceReferenceSoap.ReadUserDataRequest inValue = new WPF_App.ServiceReferenceSoap.ReadUserDataRequest();
            inValue.Body = new WPF_App.ServiceReferenceSoap.ReadUserDataRequestBody();
            return ((WPF_App.ServiceReferenceSoap.WebServiceSoap)(this)).ReadUserDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_App.ServiceReferenceSoap.CreateUserDataResponse WPF_App.ServiceReferenceSoap.WebServiceSoap.CreateUserData(WPF_App.ServiceReferenceSoap.CreateUserDataRequest request) {
            return base.Channel.CreateUserData(request);
        }
        
        public WPF_App.ServiceReferenceSoap.UserData CreateUserData(WPF_App.ServiceReferenceSoap.UserData requestData) {
            WPF_App.ServiceReferenceSoap.CreateUserDataRequest inValue = new WPF_App.ServiceReferenceSoap.CreateUserDataRequest();
            inValue.Body = new WPF_App.ServiceReferenceSoap.CreateUserDataRequestBody();
            inValue.Body.requestData = requestData;
            WPF_App.ServiceReferenceSoap.CreateUserDataResponse retVal = ((WPF_App.ServiceReferenceSoap.WebServiceSoap)(this)).CreateUserData(inValue);
            return retVal.Body.CreateUserDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.CreateUserDataResponse> WPF_App.ServiceReferenceSoap.WebServiceSoap.CreateUserDataAsync(WPF_App.ServiceReferenceSoap.CreateUserDataRequest request) {
            return base.Channel.CreateUserDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.CreateUserDataResponse> CreateUserDataAsync(WPF_App.ServiceReferenceSoap.UserData requestData) {
            WPF_App.ServiceReferenceSoap.CreateUserDataRequest inValue = new WPF_App.ServiceReferenceSoap.CreateUserDataRequest();
            inValue.Body = new WPF_App.ServiceReferenceSoap.CreateUserDataRequestBody();
            inValue.Body.requestData = requestData;
            return ((WPF_App.ServiceReferenceSoap.WebServiceSoap)(this)).CreateUserDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_App.ServiceReferenceSoap.UpdateUserDataResponse WPF_App.ServiceReferenceSoap.WebServiceSoap.UpdateUserData(WPF_App.ServiceReferenceSoap.UpdateUserDataRequest request) {
            return base.Channel.UpdateUserData(request);
        }
        
        public WPF_App.ServiceReferenceSoap.UserData UpdateUserData(WPF_App.ServiceReferenceSoap.UserData requestData) {
            WPF_App.ServiceReferenceSoap.UpdateUserDataRequest inValue = new WPF_App.ServiceReferenceSoap.UpdateUserDataRequest();
            inValue.Body = new WPF_App.ServiceReferenceSoap.UpdateUserDataRequestBody();
            inValue.Body.requestData = requestData;
            WPF_App.ServiceReferenceSoap.UpdateUserDataResponse retVal = ((WPF_App.ServiceReferenceSoap.WebServiceSoap)(this)).UpdateUserData(inValue);
            return retVal.Body.UpdateUserDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.UpdateUserDataResponse> WPF_App.ServiceReferenceSoap.WebServiceSoap.UpdateUserDataAsync(WPF_App.ServiceReferenceSoap.UpdateUserDataRequest request) {
            return base.Channel.UpdateUserDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF_App.ServiceReferenceSoap.UpdateUserDataResponse> UpdateUserDataAsync(WPF_App.ServiceReferenceSoap.UserData requestData) {
            WPF_App.ServiceReferenceSoap.UpdateUserDataRequest inValue = new WPF_App.ServiceReferenceSoap.UpdateUserDataRequest();
            inValue.Body = new WPF_App.ServiceReferenceSoap.UpdateUserDataRequestBody();
            inValue.Body.requestData = requestData;
            return ((WPF_App.ServiceReferenceSoap.WebServiceSoap)(this)).UpdateUserDataAsync(inValue);
        }
    }
}
